name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: show files
      run: ls
    - name: dir
      run: mkdir build
    - name: show files
      run: ls
    - name: cmake
      run: cd build && cmake ..
    - name: make
      run: cd build && make
